### ISSUE TITLE
Random reboots on bacon, 2015/12/23, CM13

### ISSUE THREAD

**Issue by xingrz** [sultanxda/android#1]
Still reboots after flashed `bacon-old-rmt-storage_2015-12-23.zip`

**Comment by kerneltoast** [comment]
Several people reported that flashing that fixed their random reboots. That file was meant to address the full reboots (reboot to OnePlus logo); it is not meant to address any kind of soft reboots. Also, installing a custom kernel can cause reboots.

Without more details, I cannot attempt to investigate your reboots.

**Comment by mmhobi7** [comment]
Yo, what did you change with rmt storage

On stock CM it crashes a lot too btw

**Comment by xingrz** [comment]
@sultanxda I'm not using any custom kernel. Everything is from your unofficial cm13.

It solves after I flashed back to 20151221. I'm flashing 20151224 to see if the problem is finally fixed.

**Comment by xingrz** [comment]
Great job, seems fixed in 20151224.
