### ISSUE TITLE
Touch screen freezes on bacon, CM13, since 2015/12/11

### ISSUE THREAD

**Issue by xingrz** [sultanxda/android#2]
I use this build since 2015/12/11, so I don't know if the problem come before or after 2015/12/11.

The touch screen freezes randomly, about a period of 1 or 2 minutes.

I can suggest that the freeze happen on touch screen because when it freezes, I can see the animation's keep on playing. Also it may usually happen after an `ACTION_DOWN` and before an `ACTION_UP`.

**Comment by kerneltoast** [comment]
The touchscreen kernel driver and firmware have not been modified recently (thus they cannot be at fault), so this is not an issue that I will look into. I only work on device-specific software components.
